spring.datasource.url=jdbc:postgresql://dpg-d8noccmrnols73e0bhig-a/teamsync_db_wzwj
spring.datasource.username=teamsync_db_wzwj_user
spring.datasource.password=mj9GiLrZdROywT2gmG2IHUnqGKQqQvoi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
server.port=${PORT:8080}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
